Conflicts in versions
nltk is listed twice with hard requirements nltk==3.5 and nltk==3.8 and so it results in conflicts.
and huggingface-hub results in the following error, so change it
 ERROR: Cannot install huggingface-hub==0.0.12 and sentence-transformers==2.2.2 because these package versions have conflicting dependencies.